# Generated by Django 5.1.15 on 2026-07-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        ('principles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Frontend icon key.', max_length=40)),
                ('accent', models.CharField(blank=True, help_text='Frontend design-token key.', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('origin', models.CharField(choices=[('editorial', 'Editorial'), ('ai', 'AI-generated')], default='editorial', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=12)),
                ('version', models.PositiveIntegerField(default=1)),
                ('attribution', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('ai_prompt_kind', models.CharField(blank=True, max_length=100)),
                ('ai_generated_at', models.DateTimeField(blank=True, null=True)),
                ('ai_reviewed', models.BooleanField(default=False, help_text='Has an editor reviewed this AI output?')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='library.passage')),
                ('related_principles', models.ManyToManyField(blank=True, related_name='annotations', to='principles.principle')),
                ('annotation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='annotations.annotationtype')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnnotationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citation', models.CharField(max_length=400)),
                ('url', models.URLField(blank=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='annotations.annotation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('term', models.CharField(max_length=120)),
                ('meaning', models.TextField()),
                ('etymology', models.TextField(blank=True)),
                ('passages', models.ManyToManyField(blank=True, related_name='definitions', to='library.passage')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='PassageRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('parallel', 'Parallel idea'), ('contrast', 'Contrasting idea'), ('develops', 'Develops further'), ('references', 'References')], default='parallel', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('from_passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_out', to='library.passage')),
                ('to_passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_in', to='library.passage')),
            ],
        ),
        migrations.CreateModel(
            name='VisualisationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Written explanation — also serves as the accessible text alternative.')),
                ('component_key', models.CharField(help_text="Frontend component key, e.g. 'vibration'.", max_length=60)),
                ('passage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualisations', to='library.passage')),
                ('principle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visualisations', to='principles.principle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['passage', 'status'], name='annotations_passage_5d00d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='passagerelationship',
            constraint=models.UniqueConstraint(fields=('from_passage', 'to_passage'), name='unique_passage_relationship'),
        ),
    ]
