# Generated by Django 5.1.15 on 2026-07-16 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('chapter', 'Chapter'), ('section', 'Section'), ('paragraph', 'Paragraph'), ('passage', 'Passage'), ('annotation', 'Annotation'), ('principle', 'Principle'), ('visualisation', 'Visualisation')], max_length=16)),
                ('object_id', models.CharField(max_length=120)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('chapter_slug', models.SlugField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'kind'], name='bookmarks_b_user_id_d898f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'object_id'), name='unique_bookmark_per_target')],
            },
        ),
    ]
