# Generated by Django 5.1.15 on 2026-07-16 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('style', models.CharField(choices=[('gold', 'Tarnished gold'), ('ember', 'Ember'), ('violet', 'Desaturated violet'), ('sage', 'Oxidised sage')], default='gold', max_length=12)),
                ('note', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='library.paragraph')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'paragraph'], name='highlights__user_id_b4427c_idx')],
            },
        ),
    ]
