# Generated by Django 5.1.15 on 2026-07-16 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('passage', 'Passage'), ('annotation', 'Annotation'), ('chapter', 'Chapter'), ('principle', 'Principle'), ('visualisation', 'Visualisation'), ('journal', 'Journal entry')], max_length=16)),
                ('object_id', models.CharField(max_length=120)),
                ('chapter_slug', models.SlugField(blank=True)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('pinned', models.BooleanField(default=False)),
                ('linked_principle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notes', to='principles.principle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'kind', 'object_id'], name='notes_usern_user_id_a72b02_idx')],
            },
        ),
    ]
