# Generated by Django 5.1.15 on 2026-07-16 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Principle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('aphorism', models.TextField(blank=True, help_text='The axiom associated with the principle, with source.')),
                ('aphorism_source', models.CharField(blank=True, max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('plain_explanation', models.TextField(blank=True)),
                ('deep_interpretation', models.TextField(blank=True)),
                ('editorial_note', models.TextField(blank=True, help_text='Editorial context, e.g. how historical terminology differs from modern usage.')),
                ('accent', models.CharField(blank=True, help_text='Design-token key used by the frontend.', max_length=40)),
                ('symbol', models.CharField(blank=True, help_text='Symbol key for the frontend icon system.', max_length=40)),
                ('visualisation_key', models.CharField(blank=True, max_length=40)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='PrincipleExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('modern', 'Modern example'), ('practical', 'Practical everyday example')], default='modern', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='principles.principle')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrincipleMisunderstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.CharField(help_text='The common misreading, stated plainly.', max_length=300)),
                ('clarification', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misunderstandings', to='principles.principle')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrincipleReflectionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('context', models.CharField(choices=[('principle', 'Principle study'), ('chapter', 'End of chapter'), ('daily', 'Daily reflection')], default='principle', max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('principle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_prompts', to='principles.principle')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PrincipleRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('complements', 'Complements'), ('contrasts', 'Contrasts with'), ('builds_on', 'Builds on'), ('expresses', 'Expresses')], default='complements', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('from_principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_out', to='principles.principle')),
                ('to_principle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_in', to='principles.principle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_principle', 'to_principle', 'kind'), name='unique_principle_relationship')],
            },
        ),
    ]
